In [1]:
using TextAnalysis




In [2]:
using MultivariateStats

In [3]:
using Clustering

In [4]:
pathname="G:/jupyterr/Adams_1827.txt"

"G:/jupyterr/Adams_1827.txt"

In [5]:
fd=FileDocument(pathname)

A FileDocument
 * Language: Languages.English()
 * Title: G:/jupyterr/Adams_1827.txt
 * Author: Unknown Author
 * Timestamp: Unknown Time
 * Snippet: Fellow Citizens of the Senate and of the House of 

In [6]:
language(fd)

Languages.English()

In [7]:
title(fd)
author(fd)

"Unknown Author"

In [8]:
ngrams(fd,2)

Dict{AbstractString,Int64} with 5094 entries:
  "than three"           => 1
  "over-reaching treaty" => 1
  "and from"             => 1
  "completion of"        => 1
  "congress ,"           => 2
  "of revenue"           => 1
  ", 1822"               => 3
  "Indians were"         => 1
  "which this"           => 1
  "colonial ports"       => 4
  "of experience"        => 1
  "advantages are"       => 1
  "council of"           => 1
  "applied as"           => 1
  "July 1"               => 1
  "to a"                 => 6
  "is interwoven"        => 1
  "the moment"           => 2
  "present Government"   => 1
  "under extended"       => 1
  "lands and"            => 1
  "debts contracted"     => 1
  "foreign nations"      => 1
  "upon an"              => 1
  "\$ 16,886,581.32"     => 1
  ⋮                      => ⋮

In [9]:
crps=Corpus([FileDocument(pathname)])

A Corpus with 1 documents:
 * 0 StringDocument's
 * 1 FileDocument's
 * 0 TokenDocument's
 * 0 NGramDocument's

Corpus's lexicon contains 0 tokens
Corpus's index contains 0 tokens

In [10]:
lexicon(crps)

Dict{String,Int64}()

In [11]:
update_lexicon!(crps)
lexicon(crps)

Dict{String,Int64} with 1891 entries:
  "1"               => 8
  "neither."        => 1
  "mutual"          => 5
  "enjoy"           => 1
  "recommending"    => 1
  "Cape"            => 1
  "regular"         => 1
  "Empire"          => 1
  "lightly"         => 1
  "adjusted"        => 1
  "surveyed"        => 1
  "during"          => 2
  "whose"           => 2
  "concernment"     => 1
  "favor"           => 1
  "warrior-patriot" => 1
  "peace"           => 7
  "signalized"      => 1
  "scene"           => 1
  "giving"          => 1
  "those"           => 16
  "sustained"       => 4
  "5,774,000"       => 1
  "accommodation"   => 1
  "remission"       => 1
  ⋮                 => ⋮

In [12]:
inverse_index(crps)

Dict{String,Array{Int64,1}}()

In [13]:
update_inverse_index!(crps)
inverse_index(crps)

Dict{String,Array{Int64,1}} with 1891 entries:
  "1"               => [1]
  "neither."        => [1]
  "mutual"          => [1]
  "enjoy"           => [1]
  "recommending"    => [1]
  "Cape"            => [1]
  "regular"         => [1]
  "Empire"          => [1]
  "lightly"         => [1]
  "adjusted"        => [1]
  "surveyed"        => [1]
  "during"          => [1]
  "whose"           => [1]
  "concernment"     => [1]
  "favor"           => [1]
  "warrior-patriot" => [1]
  "peace"           => [1]
  "signalized"      => [1]
  "scene"           => [1]
  "giving"          => [1]
  "those"           => [1]
  "sustained"       => [1]
  "5,774,000"       => [1]
  "accommodation"   => [1]
  "remission"       => [1]
  ⋮                 => ⋮

In [14]:
mat=DocumentTermMatrix(crps)

A 1 X 1891 DocumentTermMatrix

In [15]:
dtm(mat)

1×1891 SparseArrays.SparseMatrixCSC{Int64,Int64} with 1891 stored entries:
  [1,    1]  =  27
  [1,    2]  =  4
  [1,    3]  =  1
  [1,    4]  =  1
  [1,    5]  =  365
  [1,    6]  =  15
  [1,    7]  =  8
  [1,    8]  =  1
  [1,    9]  =  1
  [1,   10]  =  1
  [1,   11]  =  2
  [1,   12]  =  1
  ⋮
  [1, 1879]  =  10
  [1, 1880]  =  10
  [1, 1881]  =  1
  [1, 1882]  =  3
  [1, 1883]  =  1
  [1, 1884]  =  11
  [1, 1885]  =  5
  [1, 1886]  =  2
  [1, 1887]  =  10
  [1, 1888]  =  6
  [1, 1889]  =  1
  [1, 1890]  =  1
  [1, 1891]  =  1

In [16]:
dtm(mat, :dense)

1×1891 Array{Int64,2}:
 27  4  1  1  365  15  8  1  1  1  2  1  …  1  3  1  11  5  2  10  6  1  1  1

In [17]:
tf_idf(mat)

1×1891 SparseArrays.SparseMatrixCSC{Float64,Int64} with 1891 stored entries:
  [1,    1]  =  0.0
  [1,    2]  =  0.0
  [1,    3]  =  0.0
  [1,    4]  =  0.0
  [1,    5]  =  0.0
  [1,    6]  =  0.0
  [1,    7]  =  0.0
  [1,    8]  =  0.0
  [1,    9]  =  0.0
  [1,   10]  =  0.0
  [1,   11]  =  0.0
  [1,   12]  =  0.0
  ⋮
  [1, 1879]  =  0.0
  [1, 1880]  =  0.0
  [1, 1881]  =  0.0
  [1, 1882]  =  0.0
  [1, 1883]  =  0.0
  [1, 1884]  =  0.0
  [1, 1885]  =  0.0
  [1, 1886]  =  0.0
  [1, 1887]  =  0.0
  [1, 1888]  =  0.0
  [1, 1889]  =  0.0
  [1, 1890]  =  0.0
  [1, 1891]  =  0.0

In [18]:
text(crps[1])

"Fellow Citizens of the Senate and of the House of Representatives:\r\n\r\nA revolution of the seasons has nearly been completed since the\r\nrepresentatives of the people and States of this Union were last\r\nassembled at this place to deliberate and to act upon the common\r\nimportant interests of their constituents. In that interval the never\r\nslumbering eye of a wise and beneficent Providence has continued its\r\nguardian care over the welfare of our beloved country; the blessing of\r\nhealth has continued generally to prevail throughout the land; the\r\nblessing of peace with our brethren of the human race has been enjoyed\r\nwithout interruption; internal quiet has left our fellow citizens in\r\nthe full enjoyment of all their rights and in the free exercise of all\r\ntheir faculties, to pursue the impulse of their nature and the\r\nobligation of their duty in the improvement of their own condition; the\r\nproductions of the soil, the exchanges of commerce, the vivifying\r\nlab

In [1]:
using Distances, Statistics
using MultivariateStats
using PyPlot
using WordTokenizers
using TextAnalysis
using DelimitedFiles

In [2]:
function load_embeddings(embedding_file)
    local LL, indexed_words, index
    indexed_words = Vector{String}()
    LL=Vector{Vector{Float32}}()
    open(embedding_file) do f
        index = 1
        for line in eachline(f)
            xs=split(line)
            word=xs[1]
            push!(indexed_words, word)
            push!(LL, parse.(Float32,xs[2:end]))
            index += 1
        end
    end
    return reduce(hcat,LL), indexed_words
end

load_embeddings (generic function with 1 method)

In [6]:
pathname2="G:/jupyterr/glove.6B.50d.txt"

"G:/jupyterr/glove.6B.50d.txt"

In [7]:
embedding, vocab = load_embeddings(pathname2)
vec_size, vocab_size = size(embedding)
println("Each vector is represented by a vector with $vec_size features. The vocab size is $vocab_size")

Each vector is represented by a vector with 50 features. The vocab size is 400000


In [5]:
vec_idx(s) = findfirst(x -> x==s, vocab)
  

vec_idx (generic function with 1 method)

In [8]:
vec_idx("king")

692

In [ ]:
vec_idx()

In [32]:
using TextAnalysis: NaiveBayesClassifier, fit!, predict

In [9]:
vec_idx("queen")

2061

In [10]:
function vec(s)
    if vec_idx(s)!=nothing
        embedding[:,vec_idx(s)]
    end
end
vec("nongame")

50-element Array{Float32,1}:
  0.35286
 -0.23699
 -0.77357
  0.74114
 -0.012065
 -0.36192
 -0.39925
 -0.27894
  1.7881
 -0.26777
 -0.36849
  0.11557
  1.3973
  ⋮
 -0.86715
  0.10879
 -0.58138
 -0.58457
  0.60059
  0.67574
  0.40177
 -0.19689
  0.2758
  0.22438
 -0.027037
  0.52948

In [11]:
cosine(x,y)=1-cosine_dist(x,y)

cosine (generic function with 1 method)

In [12]:
cosine(vec("dog"),vec("puppy"))

0.7754921f0

In [15]:
cosine(vec("important"),vec("vital"))

0.7793778f0

In [14]:
cosine(vec("dog"),vec("god"))

0.45620286f0

In [15]:
vec("cheese")

50-element Array{Float32,1}:
 -0.053903
 -0.30871
 -1.3285
 -0.43342
  0.31779
  1.5224
 -0.6965
 -0.037086
 -0.83784
  0.074107
 -0.30532
 -0.1783
  1.2337
  ⋮
  1.9502
 -0.53274
  1.1359
  0.20027
  0.02245
 -0.39379
  1.0609
  1.585
  0.17889
  0.43556
  0.68161
  0.066202

In [16]:
function closest(v, n=15)
    list=[(x,cosine(embedding'[x,:],v)) for x in 1:size(embedding)[2]]
    topn_idx=sort(list, by=x -> x[2], rev=true)[1:n]
    return [vocab[a] for(a,_) in topn_idx]
end

closest (generic function with 2 methods)

In [17]:
closest(vec("swim"))

15-element Array{String,1}:
 "swim"
 "swimming"
 "swims"
 "swam"
 "surfing"
 "swimmers"
 "diving"
 "jumping"
 "paddling"
 "rowing"
 "sailing"
 "surf"
 "skate"
 "ride"
 "kayaking"

In [18]:
closest(vec("lion"))

15-element Array{String,1}:
 "lion"
 "dragon"
 "elephant"
 "beast"
 "golden"
 "cat"
 "unicorn"
 "bear"
 "rabbit"
 "spider"
 "mermaid"
 "rooster"
 "serpent"
 "rainbow"
 "vampire"

In [24]:
closest(vec("fire")+vec("heat"))

15-element Array{String,1}:
 "heat"
 "fire"
 "ground"
 "fires"
 "heavy"
 "water"
 "cold"
 "light"
 "burn"
 "burning"
 "blowing"
 "smoke"
 "inside"
 "wind"
 "hours"

In [19]:
closest(vec("flower")+vec("gardner"))

15-element Array{String,1}:
 "flower"
 "wood"
 "flowers"
 "green"
 "garden"
 "robinson"
 "lane"
 "garland"
 "brown"
 "tree"
 "lily"
 "ellis"
 "berry"
 "stone"
 "parker"

In [21]:
closest(vec("king")+vec("queen")-vec("women"))

15-element Array{String,1}:
 "king"
 "prince"
 "coronation"
 "queen"
 "throne"
 "majesty"
 "sir"
 "lord"
 "iv"
 "brother-in-law"
 "æthelstan"
 "augustus"
 "vi"
 "sigismund"
 "castle"

In [22]:
closest(vec("himalaya")+vec(""))

15-element Array{String,1}:
 "river"
 "valley"
 "estuary"
 "basin"
 "mountains"
 "confluence"
 "flows"
 "tributary"
 "zambezi"
 "klamath"
 "rivers"
 "headwaters"
 "foothills"
 "himalaya"
 "originates"

In [43]:
closest(vec("water")+vec("ice"))

15-element Array{String,1}:
 "water"
 "ice"
 "dry"
 "sand"
 "dust"
 "snow"
 "hot"
 "salt"
 "heat"
 "surface"
 "natural"
 "covered"
 "cold"
 "ocean"
 "wet"

In [25]:
closest(mean([vec("day"), vec("night")]))

15-element Array{String,1}:
 "night"
 "day"
 "days"
 "weekend"
 "morning"
 "sunday"
 "afternoon"
 "saturday"
 "came"
 "week"
 "evening"
 "coming"
 "next"
 "on"
 "before"

In [30]:
txt=open("G:/jupyterr/book.txt") do file 
    read(file, String)
end
println("Loaded Storm Of London, length=$(length(txt)) characters")

Loaded Storm Of London, length=883111 characters


In [29]:
using WordTokenizers, TextAnalysis

function sentences(txt)
    txt= replace(txt, r"\n|\r|_|,"=>"")
    txt= replace(txt, r"[\"*();!]"=>"")
    sd=StringDocument(txt)
    prepare!(sd, strip_whitespace)
    sentences = WordTokenizers.split_sentences(sd.text)
    i=1
    for s in 1:length(sentences)
        if lenght(split(sentences[s]))>3
            sentences[i]=lowercase(replace(sentences[s], "."=>""))
            i+1
        end
    end
sentences[1000:1010]
end

sentences (generic function with 1 method)

In [31]:
function sentvec(s)
    local arr=[64]
    for w in split(sentences[s])
        if vec(w)!=nothing
            push!(arr, vec(w))
        end
    end
    if lenght(arr)==0
        ones(Float64, (50,1))*900
    else
        mean(arr)
    end
end

sentvec (generic function with 1 method)

In [32]:
sentences[20]

LoadError: MethodError: no method matching getindex(::typeof(sentences), ::Int64)

In [41]:
function closest_sent(input_str, n=200)
    mean_vec_input=mean([vec(w) for w in split(input_str)])
    list=[(x,cosine(mean_vec_input, sentvec(x))) for x in 1:lenght(sentence)]
    topn_idx=sort(list, by = x -> x[2], rev=true)[1:n]
    return [sentences[a] for (a,_) in topn_idx]
end

closest_sent (generic function with 2 methods)

In [42]:
closest_sent("my favorites food is strawberry ice creame")

LoadError: MethodError: no method matching +(::Array{Float32,1}, ::Nothing)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::PyCall.PyObject, ::Any) at C:\Users\jay patel\.julia\packages\PyCall\BcTLp\src\pyoperators.jl:13
  +(::Array, !Matched::Array...) at arraymath.jl:43
  ...